### ISSUE TITLE
Game-end dialog is counterintuitive

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/arithmetic#170] opened 2016-01-16 00:44 UTC
@kathy-phet was looking at Arithmetic with some other folks and they found it strange that when the user finishes a level and clicks "continue" they remain on the same screen. Instead, they would expect to move on to the next level, or something similar. 

@jbphet and I discussed and think that it makes the most sense to revert to the behavior where clicking continue returns the user to the level selection screen. The user can still click on that level again and see the completed board if they want to reflect or if it is part of a classroom activity, so that functionality will not be lost. This change can be done quickly so that Kathy can show a new version sooner rather than later. 

@kathy-phet also proposed having two buttons on the dialog- something along the lines of "continue" and "review" so that the user has two choices. However, this diverts quite a bit from the common code and would require a lot more developer time to implement, so if we decide to go this route it would not happen as quickly. 

@ariel-phet any thoughts on this?

**Comment by ariel-phet** [comment] 2016-01-16 01:08
As @amanda-phet mentioned in https://github.com/phetsims/arithmetic/issues/163 this was an intended behavior.

Of course, if @kathy-phet wants it changed, it would make most sense just to go the normal route and not have a special "review" button.

So yes, lets have clicking return the user to the level selection screen.

**Comment by jbphet** [comment] 2016-01-20 18:52
The issue that records the decision to stay on the table screen and not go back to level selection is https://github.com/phetsims/arithmetic/issues/129, specifically https://github.com/phetsims/arithmetic/issues/129#issuecomment-150699062.

Also, @arouinfar asked about the behavior where it remains on the table in https://github.com/phetsims/arithmetic/issues/163, so there has been some internal questioning of this behavior too.

**Comment by jbphet** [comment] 2016-01-20 21:05
Done, I'll ask in status meeting whether the warrants a maintenance release.

**Comment by arouinfar** [comment] 2016-01-20 21:14
:+1:

**Comment by phet-steele** [comment] 2016-01-20 21:25
BTW @jbphet, this works fine.

**Comment by jbphet** [comment] 2016-01-26 20:23
In status meeting, @kathy-phet decided that yes, a maintenance release should be done to make this change available to the public.

**Comment by jbphet** [comment] 2016-01-29 21:40
Maintenance release completed, closing.

**Closed by jbphet** 2016-01-29 21:40 UTC
Labels: enhancement
