### ISSUE TITLE
No 'hand' image if user makes second answer attempt without 'Try Again'

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/arithmetic#165] opened 2015-12-15 01:32 UTC
Possibly related to #160, If the user makes a second attempt at the answer in 'Factor' screen, the hand icon does not appear.  The table cells also do not highlight.

**Comment by amanda-phet** [comment] 2015-12-15 04:12
Does this happen after clicking the try again button? Or only if you try again without clicking the try again button?

**Comment by amanda-phet** [comment] 2015-12-15 04:34
I ask because this shouldn't happen if you've clicked the try again button. However, we wanted users to be able to try again by clicking the board (and not requiring that they click the try again button), so this is what makes that possible.

**Comment by jessegreenberg** [comment] 2015-12-15 05:47
Ah OK, that makes sense.  It only happens without clicking the try again button, If the user presses 'Try Again' the hand appears and the table highlights correctly.  I guess I expected the table cells to highlight without pressing 'Try Again'.

![untitled_video](https://cloud.githubusercontent.com/assets/6396244/11803064/4c7e73d8-a2b4-11e5-9bc4-8c42119492c2.gif)

**Comment by jessegreenberg** [comment] 2015-12-15 05:48
Ah, but now I see that the current behavior allows the user to count the area to learn why the factor is incorrect.

**Comment by ariel-phet** [comment] 2015-12-15 07:32
yes, this is intended behavior, not a bug. closing

**Closed by ariel-phet** 2015-12-15 07:32 UTC
Labels: bug
