### ISSUE TITLE
Reset button does not reset game screens

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/arithmetic#146] opened 2015-12-02 17:13 UTC
Test device: Personal Mac
Operating System: OSX 10.11
Browser: Safari 9.0
Problem description: The reset button does not reset game screens. That is, if you play any of the games "Multiply","Factor","Divide" on any of the difficulties: hitting back and reset at any point after answering some questions does not reset the game screen. The answers from prior to reset remain on the multiplication table.

Steps to reproduce:
-Open sim
-Pick any game on any difficulty
-Answer one question
-Hit the back button
-Hit reset
Open the same game again

Severity: High
Screenshots:

Troubleshooting information (do not edit):
Name: ‪Arithmetic‬
URL: http://www.colorado.edu/physics/phet/dev/html/arithmetic/1.0.0-dev.16/arithmetic_en.html
Version: 1.0.0-dev.16 2015-12-01 22:20:53 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11) AppleWebKit/601.1.56 (KHTML, like Gecko) Version/9.0 Safari/601.1.56
Language: en-us
Window: 1240x712
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (2.1 INTEL-10.8.77)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"arithmetic":{"sha":"da928fe4","branch":"master"},"assert":{"sha":"3921bc37","branch":"master"},"axon":{"sha":"fffc6c30","branch":"master"},"babel":{"sha":"90f9f553","branch":"master"},"brand":{"sha":"c9282935","branch":"master"},"chipper":{"sha":"b1b72ba8","branch":"master"},"dot":{"sha":"b8ec76e8","branch":"master"},"joist":{"sha":"3bd993e7","branch":"master"},"kite":{"sha":"a4907ccc","branch":"master"},"phet-core":{"sha":"73a034c6","branch":"master"},"phetcommon":{"sha":"e074b239","branch":"master"},"scenery":{"sha":"596fce54","branch":"master"},"scenery-phet":{"sha":"ab056b47","branch":"master"},"sherpa":{"sha":"be8c4fc9","branch":"master"},"sun":{"sha":"bf8586ef","branch":"master"},"tandem":{"sha":"e98bd8c3","branch":"master"},"vegas":{"sha":"b7bb8c39","branch":"master"},"vibe":{"sha":"f09e9c6e","branch":"master"}}

**Comment by brroberts1231** [comment] 2015-12-03 22:13
Reproduces on windows edge, chrome, and firefox

**Comment by phet-steele** [comment] 2015-12-04 18:31
Much like #148, proceeding through the level like normal resets everything correctly.

**Comment by jbphet** [comment] 2015-12-04 19:37
I implemented a fix for this that refreshes the appearance of the table when transitioning out of the SELECTING_LEVEL state.  It seems like it would be a bit more, let's say, "solid" to change the LevelModel so that it sent out an event each time the list of answered cells changed, and link the updates of the view to this event, but that would be a bit more ambitious.  I'll leave this open until some other issues are resolved and will decide the the event-based approach is worth doing based on whether it would fix other issues and based on how much time I have.

**Comment by phet-steele** [comment] 2015-12-09 18:10
Multiply and Divide screens reset as expected in 1.0.0-dev.17. However if the factor screen is reset, any previously, fully completed levels will be uninteractive.

**Comment by jbphet** [comment] 2015-12-09 21:05
@phet-steele - I'm not able to duplicate the behavior that you're describing.  Can you provide a bit more detail as to the exact sequence?

**Comment by jbphet** [comment] 2015-12-09 21:34
@phet-steele - Never mind, I was able to find it.  Looks like I need to manually play the level until complete, then go back to the level selection screen, hit reset, and go back.  The board is cleared, but interaction doesn't work.  I'm all over it.

**Comment by jbphet** [comment] 2015-12-11 21:08
Tested this on version 1.0.0-rc.1 to make sure it was fixed.  Looks good.  Closing.

**Closed by jbphet** 2015-12-11 21:08 UTC
