### ISSUE TITLE
[Arithmetic] missing keyboard input

### ISSUE THREAD

**Issue by MDmitrieva** [phetsims/arithmetic#7] opened 2014-06-11 11:12 UTC
that if the user is using a mouse and keyboard, the sim should allow number entry with the keyboard so that they don’t have to use the mouse if they don’t want.

**Comment by oliver-phet** [comment] 2016-04-04 16:00
Another user reported to phethelp:
 

> on the new arithmetic simulation (both online and on the download), I am unable to type in the answer to the problems. I can only use the on-screen number box. I had no such problem with the legacy version. Is there any way to fix this?

**Comment by oliver-phet** [comment] 2017-12-11 15:33
Another request for this feature received 12/11:

> The app is working well. The only trouble is we would like to use the physical keyboard like in the older version.

**Comment by amanda-phet** [comment] 2017-12-11 20:49
If it is an iPad app would the keyboard pop up and cover the sim? Or would it be limited to external keyboards that are attached/plugged in? 

When we get to keyboard navigation for this sim, I wonder if it would make keyboard entry possible. because right now we don't have a design for keypad entry so it seems like that would be the time to tackle it. Tagging @jessegreenberg and @emily-phet to consider this when we get to this sim.

**Comment by jbphet** [comment] 2017-12-12 16:02
Since there is a keypad within the sim, having one pop up on iPad seems undesirable.  Hopefully it is possible to support key entry on desktop and not trigger the appearance of the keypad in iOS, but this will need to be investigated as part of the effort.

**Comment by jbphet** [comment] 2017-12-12 16:03
Reopening, since the issue is being reconsidered.

**Comment by jessegreenberg** [comment] 2017-12-13 06:06
> If it is an iPad app would the keyboard pop up and cover the sim?

By default, yes I expect it will cover the sim. Number entry is possible but not something we have worked on yet. Making sure that an on screen keyboard does not appear for mobile devices will be part of this investigation.

**Comment by emily-phet** [comment] 2018-01-07 23:51
Is this sim being actively worked on? If not, and no sims with a keyboard are being worked on, let's wait until one comes up to dig into this. Otherwise, it would be worth taking a little time to see if we can stop the triggering of the onscreen keyboard on mobile devices, and then discuss next steps once we have that info. @jbphet @jessegreenberg

**Comment by jessegreenberg** [comment] 2018-01-08 17:31
At this time, the a11y team is not working on any other sims with a number input that require keyboard input like this.

I also do not think this sim is being actively worked on, but @jbphet please correct me if I am wrong.

**Comment by jessegreenberg** [comment] 2018-01-08 17:33
I noticed that the cursor in this sim blinks whether or not the number readout has keyboard focus, which makes it look like it always has focus. That could be something to talk about when we return to this sim for a11y.

**Comment by jbphet** [comment] 2018-01-08 19:55
@jessegreenberg - you are correct, there is no active development on the main functionality of this simulation.  I'll set the priority to deferred and unassign for now.

**Comment by marlitas** [comment] 2023-11-16 20:19
This issue does not seem like it would be within the scope of the upcoming Arithmetic region and culture publication, so I will leave as deferred. @amanda-phet let me know if you think otherwise.

**Comment by amanda-phet** [comment] 2023-12-08 19:30
Have any sims with numberPad (I think that's the name) been developed yet with alt input? It seems like that is the time to tackle how to better design the experience with the numberPad.

**Comment by oliver-phet** [comment] 2023-12-08 19:55
> Have any sims with numberPad (I think that's the name) been developed yet with alt input? It seems like that is the time to tackle how to better design the experience with the numberPad.

My Solar System
https://github.com/phetsims/my-solar-system/issues/86
https://github.com/phetsims/scenery-phet/issues/790

I know there have been various issues around keyboard input and I've commented on a few in the past... I really dislike the current input experience and would have a strong preference for moving toward default OS keyboard support!

**Comment by marlitas** [comment] 2023-12-08 20:01
I think this is somewhat covered by the work needing to be done here: https://github.com/phetsims/scenery-phet/issues/283

It was added as a dev priority, but I'm not sure that will get finalized in time for Arithmetic...

**Comment by pixelzoom** [comment] 2023-12-15 19:22
Also noted during today's design discussion.  The blinking cursor is probably something that was ported from Flash by MLL (search for "blinking of cursor" in EquationNode.js).   If you can't use the keyboard to type numbers in the HTML5 version, then that cursor is totally misleading -- I (for example) had to be told by @amanda-phet to use the keypad.  So if it turns out that typing numbers is not possible, I recommend deleting the blinking cursor, and instead highlight the '?' in some way (outilne or background fill) to emphasize it.

**Comment by marlitas** [comment] 2023-12-18 19:16
@jessegreenberg and I met about this today, and we believe that there is a straightforward solution that allows Arithmetic to use Keypad and keyboard entry without enabling alternative input. We also discussed that the blinking cursor seems helpful in those cases.

**Comment by marlitas** [comment] 2024-01-18 19:44
Arithmetic now has keyboard input with the above commits. @jessegreenberg do you mind reviewing for the changes in scenery and scenery-phet?

**Comment by marlitas** [comment] 2024-01-18 19:50
@KatieWoe or @Nancy-Salpepi, @jbphet brought up a question about how this might work with iPad. 

I don't have one to test on. Would either of you be able to check and see if this now triggers the keyboard on iPad in a way that obscures the sim?

**Comment by Nancy-Salpepi** [comment] 2024-01-18 22:18
I just checked the iPad and as Jesse indicated in https://github.com/phetsims/arithmetic/issues/7#issuecomment-1899141324, the keyboard doesn't popup at all.

**Comment by marlitas** [comment] 2024-02-09 21:05
I believe this can be closed now. Thanks everyone for their help here!

**Closed by marlitas** 2024-02-09 21:05 UTC
Labels: design:general, status:ready-for-review
