### ISSUE TITLE
Touch screens require double tap to select answer in factor

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/arithmetic#164] opened 2015-12-15 01:21 UTC
For a touch screen, it takes two taps to select an answer for 'Factor' game.  One tap to 'hover' over the answer and another to 'submit' the answer.  

Was tapping twice the designed behavior for touch screens?  It was not the interface I was expecting.

**Comment by ariel-phet** [comment] 2015-12-15 03:52
@jessegreenberg this was the intended behavior....the reason is, we felt that a "hover" was needed so that on a touch interface you get the feedback of the "area model" (ie showing the rectangle of one number multiplied by another). I believe this worked fine in interviews.

@amanda-phet please correct me if I am wrong.

**Comment by amanda-phet** [comment] 2015-12-15 04:02
This behavior is intentional and is addressed in #116 . In iPad interviews it worked very well and a student even said he was submitting his answer as he tapped again, so it seemed natural in that context. It might be unexpected after being on a laptop and then encountering it on an iPad, though, but most students will probably encounter only one platform at a time.

**Closed by amanda-phet** 2015-12-15 04:02 UTC
Labels: question
